# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77f62cb1e85de54899ca4fee3c4049691c8c636681a81736858d0690330779426d61bcfd44db2b035b90527e2dbb7b94ec83c9aa4eb40b429f00d804867961e9

test:
  secret_key_base: a0a4a8b1f7a0a42c0248f86f1980bcc5638321db92ce5aeb0582adaf51614ad218c3b25d29705ec7e1b67e552d4e6feb1dec299cf2906639f85f8622e297af52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
